a = int(input("Enter First number: "))
b = int(input("Enter Second number: "))
print( "Addition :", a + b)
print( "subtraction :", a - b)
print( " Multiplication :", a*b)
print( " Divison :", a /  b)
print( " Remainder :", a % b)